continents/urls.py
from django.urls import path
from continents.views import ContinentsView

app_name = 'continents'

urlpatterns = [
    path("", ContinentsView.as_view(), name="home")
]

countries/urls.py
from django.urls import path
from countries.views import (
	CountryDetailView, CountryDetailIDView, CountrySearchView,
)

urlpatterns = [
    path("search/<query>/", CountrySearchView.as_view(), name="country_search"),
    path("<int:pk>/", CountryDetailIDView.as_view(), name="country_id_detail"),
    path("<code>/", CountryDetailView.as_view(), name="country_detail")
]

geographic/urls.py
from django.contrib import admin
from django.urls import path
from countries.views import HomeView, TagsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", HomeView.as_view()),
    path("tags/", TagsView.as_view())

]

continents/models.py
from django.db import models

# Create your models here.
class Continent(models.Model):
	name = models.CharField(max_length=255)
	translate = models.CharField(max_length=255)
	color = models.CharField(max_length=255)

	def _str_(self):
		return self.name

countries/models.py
from django.db import models

class ActiveManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(active=True)


class Country(models.Model):
    CODES_CHOICES =(
        ('CO', 'colombia'),
        ('MX', 'mexico' ),
        ('USA', 'Estados Unidos'),
        ('AR', 'argentina'),
    )

    name = models.CharField(max_length=255)
    code = models.CharField(max_length=3, choices=CODES_CHOICES)
    continent = models.ForeignKey('continents.Continent', on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    objects = models.Manager()
    active_manager = ActiveManager() 

    def __str__(self):
        return self.name

people/models.py
from django.db import models

# Create your models here.
class Person(models.Model): 
	first_name = models.CharField(max_length=255)
	nacionality = models.ManyToManyField('countries.Country')
	father = models.OneToOneField('self', on_delete=models.CASCADE, null=True )

people/forms.py
from django import forms
from countries.models import Country
from people.models import Person
from django.forms import ModelForm

class RegisterForm(forms.Form):
	first_name = forms.CharField(label='first name')
    nacionality = forms.ModelMultipleChoiceField(queryset=Country.objects.all())
    father = forms.ModelChoiceField(required=False, queryset=Person.objects.all())

continents/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.
class ContinentsView(TemplateView):
	template_name = 'continents/continents.html'

	def get_context_data(self, *args, **kwargs):

		america = {
			'name': 'america',
			'translation': 'america',
			'color': '#000000',
		}

		antartida = {
			'name': 'antártida',
			'translation': 'antartida',
			'color': '#FFFF00',
		}

		europa = {
			'name': 'europa',
			'translation': 'europe',
			'color': '#F1D142',
		}

		africa = {
			'name': 'africa',
			'translation': 'africa',
			'color': '#F04261',
		}

		asia = {
			'name': 'asia',
			'translation': 'asia',
			'color': '#EE65EE',
		}

		oceania = {
			'name': 'oceania',
			'translation': 'oceania',
			'color': '#EE65DD',
		}

		continents = [
			america,
			africa,
			asia,
			oceania,
			antartida
		]

		return {'continents': continents}

countries/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.views.generic import TemplateView
from countries.models import Country
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

class HomeView(TemplateView):

	template_name = 'countries/home.html'


class CountryDetailView(TemplateView):

	template_name = 'countries/country_detail.html'


	def get_context_data(self, *args, **kwargs):

		code = kwargs['code']
		return {'code': code}


class CountryDetailIDView(DetailView):

	template_name = 'countries/country_id_detail.html'
	model = Country


class TagsView(TemplateView):

	template_name = 'countries/tags.html'

class CountrySearchView(ListView):
	template_name = 'countries/search.html'


	def get_queryset(self):
		query = self.kwargs['query']
		return Country.objects.filter(name__contains= query)

people/views.py
from django.shortcuts import render

# Create your views here.

continents/templates/continents/continent.html
<div>
<h1 style="color: {{continent.color}}">{{continent.name|title}}</h1>	
<p>ingkes: {{continent.translation}}</p>
</div>

continents/templates/continents/continents.html
{% extends "countries/base.html" %}}
{% block content %}
<h1>continents</h1>
{% for continent in continents %}
	<hr>
	{% include 'continents/continent.html' %}
	<hr>
{% endfor%}	
{% endblock %}

countries/templates/countries/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>{% block title %}Geographic {% endblock %}</title>
	</head>
	<body>
	{% block content%}
	{% endblock %}
	</body>
</html>

countries/templates/countries/country.html
<h1>name: {{country.name|title}}</h1>
<p>code: {{country.code}}</p>
{% if country.name == 'colombia' %}
	<p>yea: {{country.code}}</p> 
{% endif %}	

<p>detail url <a href="{{country.detail_url}}">Ir a detalle</a> </p>

countries/templates/countries/country_detail.html
{% extends 'countries/base.html' %}

{% block content %}

{% for country in countries %}
	{% if country.code == code %}
		{%  include 'countries/country.html'%}
	{% endif %}	
{% endfor %}

{% endblock %}

countries/templates/countries/country_id_detail.html
{% extends 'countries/base.html' %}

{% block content %}

{%  include 'countries/country.html' with country=object %}

{% endblock %}

countries/templates/countries/home.html
{% extends "countries/base.html"  %}
{% block title %}
Home
{% endblock %}
{% block content %}

	<h1> World</h1>

	{% for country in countries %}
		{% include 'countries/country.html' %}
	{% endfor %}
<p><a href="{% url "tags" %}">Ir a Tags</a></p>
<p><a href="{% url "continents:home" %}">Ir a Continents</a></p>
<p><a href="{% url "country_id_detail" id=1%}">Ir a Country con id 1</a></p>

{% endblock %}

countries/templates/countries/search.html
{% extends "countries/base.html" %}
{% block content %}
{%  for country in object_list %}
	{% include "countries/country.html" %}
{% endfor %}
{% endblock %}	

countries/templates/countries/tags.html
{% extends "countries/base.html"%}
{% block content%}

		{% comment %} texto prueba
		{% endcomment %}

		{% for country in countries %}

			<p>{{country.name}}</p>
			{% if country.name == 'colombia' %}
				Terra querida
			{% endif %}
			<p>lorem: {% lorem %}</p>
			<p>fecha actual: {% now "Y-m-d" %}</p>
			{% filter force_escape|lower %}
				%#$%
			{% endfilter %}

		{% endfor %}
		{{"PRUEBA"|capfirst}}	
{% endblock %}